name: Run Node.js Script with Playwright

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Faz checkout do código

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ajuste para a versão do Node.js que você precisa

      - name: Install dependencies
        run: |
          npm install  # Instala as dependências do seu projeto
          npx playwright install  # Instala o Playwright e o navegador necessário

      - name: Run the script
        run: node index.js  # Executa o seu script Node.js (substitua pelo seu script)
